image: alpine/edge
packages:
- ruby
- ruby-dev
- rsync
sources:
- https://git.sr.ht/~bt/vanilla-css
secrets:
- 07201d32-1451-4a8f-9bff-ce8b2232c67d
tasks:
- deploy: |
    cd vanilla-css
    rsync --rsh="ssh -o StrictHostKeyChecking=no -i ~/.ssh/07201d32-1451-4a8f-9bff-ce8b2232c67d" -rzP / bt@vanillacss.com:/var/www/vanillacss.com
